# Generated by Django 5.2.4 on 2025-07-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='services/placeholder.jpg', upload_to='services/', verbose_name='صورة الخدمة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='وصف الخدمة'),
        ),
    ]
